#[derive(Debug, Clone, Copy)]
pub enum Type {
    ET_NONE,
    ET_REL,
    ET_EXEC,
    ET_DYN,
    ET_CORE,
    ET_OS(u16),
    ET_PROC(u16),
    Unknown(u16),
}

#[derive(Debug, Clone, Copy)]
pub enum Machine {
    EM_NONE,
    EM_M32,
    EM_SPARC,
    EM_386,
    EM_68K,
    EM_88K,
    EM_IAMCU,
    EM_860,
    EM_MIPS,
    EM_S370,
    EM_MIPS_RS3_LE,
    EM_PARISC,
    EM_VPP500,
    EM_SPARC32PLUS,
    EM_960,
    EM_PPC,
    EM_PPC64,
    EM_S390,
    EM_SPU,
    EM_V800,
    EM_FR20,
    EM_RH32,
    EM_RCE,
    EM_ARM,
    EM_FAKE_ALPHA,
    EM_SH,
    EM_SPARCV9,
    EM_TRICORE,
    EM_ARC,
    EM_H8_300,
    EM_H8_300H,
    EM_H8S,
    EM_H8_500,
    EM_IA_64,
    EM_MIPS_X,
    EM_COLDFIRE,
    EM_68HC12,
    EM_MMA,
    EM_PCP,
    EM_NCPU,
    EM_NDR1,
    EM_STARCORE,
    EM_ME16,
    EM_ST100,
    EM_TINYJ,
    EM_X86_64,
    EM_PDSP,
    EM_PDP10,
    EM_PDP11,
    EM_FX66,
    EM_ST9PLUS,
    EM_ST7,
    EM_68HC16,
    EM_68HC11,
    EM_68HC08,
    EM_68HC05,
    EM_SVX,
    EM_ST19,
    EM_VAX,
    EM_CRIS,
    EM_JAVELIN,
    EM_FIREPATH,
    EM_ZSP,
    EM_MMIX,
    EM_HUANY,
    EM_PRISM,
    EM_AVR,
    EM_FR30,
    EM_D10V,
    EM_D30V,
    EM_V850,
    EM_M32R,
    EM_MN10300,
    EM_MN10200,
    EM_PJ,
    EM_OPENRISC,
    EM_ARC_COMPACT,
    EM_XTENSA,
    EM_VIDEOCORE,
    EM_TMM_GPP,
    EM_NS32K,
    EM_TPC,
    EM_SNP1K,
    EM_ST200,
    EM_IP2K,
    EM_MAX,
    EM_CR,
    EM_F2MC16,
    EM_MSP430,
    EM_BLACKFIN,
    EM_SE_C33,
    EM_SEP,
    EM_ARCA,
    EM_UNICORE,
    EM_EXCESS,
    EM_DXP,
    EM_ALTERA_NIOS2,
    EM_CRX,
    EM_XGATE,
    EM_C166,
    EM_M16C,
    EM_DSPIC30F,
    EM_CE,
    EM_M32C,
    EM_TSK3000,
    EM_RS08,
    EM_SHARC,
    EM_ECOG2,
    EM_SCORE7,
    EM_DSP24,
    EM_VIDEOCORE3,
    EM_LATTICEMICO32,
    EM_SE_C17,
    EM_TI_C6000,
    EM_TI_C2000,
    EM_TI_C5500,
    EM_TI_ARP32,
    EM_TI_PRU,
    EM_MMDSP_PLUS,
    EM_CYPRESS_M8C,
    EM_R32C,
    EM_TRIMEDIA,
    EM_QDSP6,
    EM_8051,
    EM_STXP7X,
    EM_NDS32,
    EM_ECOG1X,
    EM_MAXQ30,
    EM_XIMO16,
    EM_MANIK,
    EM_CRAYNV2,
    EM_RX,
    EM_METAG,
    EM_MCST_ELBRUS,
    EM_ECOG16,
    EM_CR16,
    EM_ETPU,
    EM_SLE9X,
    EM_L10M,
    EM_K10M,
    EM_AARCH64,
    EM_AVR32,
    EM_STM8,
    EM_TILE64,
    EM_TILEPRO,
    EM_MICROBLAZE,
    EM_CUDA,
    EM_TILEGX,
    EM_CLOUDSHIELD,
    EM_COREA_1ST,
    EM_COREA_2ND,
    EM_ARCV2,
    EM_OPEN8,
    EM_RL78,
    EM_VIDEOCORE5,
    EM_78KOR,
    EM_56800EX,
    EM_BA1,
    EM_BA2,
    EM_XCORE,
    EM_MCHP_PIC,
    EM_INTELGT,
    EM_KM32,
    EM_KMX32,
    EM_EMX16,
    EM_EMX8,
    EM_KVARC,
    EM_CDP,
    EM_COGE,
    EM_COOL,
    EM_NORC,
    EM_CSR_KALIMBA,
    EM_Z80,
    EM_VISIUM,
    EM_FT32,
    EM_MOXIE,
    EM_AMDGPU,
    EM_RISCV,
    EM_BPF,
    EM_CSKY,
    EM_LOONGARCH,
    Unknown(u16),
}

impl From<u16> for Type {
    #[inline]
    fn from(v: u16) -> Self {
        match v {
            0 => Self::ET_NONE,
            1 => Self::ET_REL,
            2 => Self::ET_EXEC,
            3 => Self::ET_DYN,
            4 => Self::ET_CORE,
            0xfe00..=0xfeff => Self::ET_OS(v),
            0xff00..=0xffff => Self::ET_PROC(v),
            _ => Self::Unknown(v),
        }
    }
}

impl From<u16> for Machine {
    fn from(v: u16) -> Self {
        match v {
            0 => Machine::EM_NONE,
            1 => Machine::EM_M32,
            2 => Machine::EM_SPARC,
            3 => Machine::EM_386,
            4 => Machine::EM_68K,
            5 => Machine::EM_88K,
            6 => Machine::EM_IAMCU,
            7 => Machine::EM_860,
            8 => Machine::EM_MIPS,
            9 => Machine::EM_S370,
            10 => Machine::EM_MIPS_RS3_LE,
            15 => Machine::EM_PARISC,
            17 => Machine::EM_VPP500,
            18 => Machine::EM_SPARC32PLUS,
            19 => Machine::EM_960,
            20 => Machine::EM_PPC,
            21 => Machine::EM_PPC64,
            22 => Machine::EM_S390,
            23 => Machine::EM_SPU,
            36 => Machine::EM_V800,
            37 => Machine::EM_FR20,
            38 => Machine::EM_RH32,
            39 => Machine::EM_RCE,
            40 => Machine::EM_ARM,
            41 => Machine::EM_FAKE_ALPHA,
            42 => Machine::EM_SH,
            43 => Machine::EM_SPARCV9,
            44 => Machine::EM_TRICORE,
            45 => Machine::EM_ARC,
            46 => Machine::EM_H8_300,
            47 => Machine::EM_H8_300H,
            48 => Machine::EM_H8S,
            49 => Machine::EM_H8_500,
            50 => Machine::EM_IA_64,
            51 => Machine::EM_MIPS_X,
            52 => Machine::EM_COLDFIRE,
            53 => Machine::EM_68HC12,
            54 => Machine::EM_MMA,
            55 => Machine::EM_PCP,
            56 => Machine::EM_NCPU,
            57 => Machine::EM_NDR1,
            58 => Machine::EM_STARCORE,
            59 => Machine::EM_ME16,
            60 => Machine::EM_ST100,
            61 => Machine::EM_TINYJ,
            62 => Machine::EM_X86_64,
            63 => Machine::EM_PDSP,
            64 => Machine::EM_PDP10,
            65 => Machine::EM_PDP11,
            66 => Machine::EM_FX66,
            67 => Machine::EM_ST9PLUS,
            68 => Machine::EM_ST7,
            69 => Machine::EM_68HC16,
            70 => Machine::EM_68HC11,
            71 => Machine::EM_68HC08,
            72 => Machine::EM_68HC05,
            73 => Machine::EM_SVX,
            74 => Machine::EM_ST19,
            75 => Machine::EM_VAX,
            76 => Machine::EM_CRIS,
            77 => Machine::EM_JAVELIN,
            78 => Machine::EM_FIREPATH,
            79 => Machine::EM_ZSP,
            80 => Machine::EM_MMIX,
            81 => Machine::EM_HUANY,
            82 => Machine::EM_PRISM,
            83 => Machine::EM_AVR,
            84 => Machine::EM_FR30,
            85 => Machine::EM_D10V,
            86 => Machine::EM_D30V,
            87 => Machine::EM_V850,
            88 => Machine::EM_M32R,
            89 => Machine::EM_MN10300,
            90 => Machine::EM_MN10200,
            91 => Machine::EM_PJ,
            92 => Machine::EM_OPENRISC,
            93 => Machine::EM_ARC_COMPACT,
            94 => Machine::EM_XTENSA,
            95 => Machine::EM_VIDEOCORE,
            96 => Machine::EM_TMM_GPP,
            97 => Machine::EM_NS32K,
            98 => Machine::EM_TPC,
            99 => Machine::EM_SNP1K,
            100 => Machine::EM_ST200,
            101 => Machine::EM_IP2K,
            102 => Machine::EM_MAX,
            103 => Machine::EM_CR,
            104 => Machine::EM_F2MC16,
            105 => Machine::EM_MSP430,
            106 => Machine::EM_BLACKFIN,
            107 => Machine::EM_SE_C33,
            108 => Machine::EM_SEP,
            109 => Machine::EM_ARCA,
            110 => Machine::EM_UNICORE,
            111 => Machine::EM_EXCESS,
            112 => Machine::EM_DXP,
            113 => Machine::EM_ALTERA_NIOS2,
            114 => Machine::EM_CRX,
            115 => Machine::EM_XGATE,
            116 => Machine::EM_C166,
            117 => Machine::EM_M16C,
            118 => Machine::EM_DSPIC30F,
            119 => Machine::EM_CE,
            120 => Machine::EM_M32C,
            131 => Machine::EM_TSK3000,
            132 => Machine::EM_RS08,
            133 => Machine::EM_SHARC,
            134 => Machine::EM_ECOG2,
            135 => Machine::EM_SCORE7,
            136 => Machine::EM_DSP24,
            137 => Machine::EM_VIDEOCORE3,
            138 => Machine::EM_LATTICEMICO32,
            139 => Machine::EM_SE_C17,
            140 => Machine::EM_TI_C6000,
            141 => Machine::EM_TI_C2000,
            142 => Machine::EM_TI_C5500,
            143 => Machine::EM_TI_ARP32,
            144 => Machine::EM_TI_PRU,
            160 => Machine::EM_MMDSP_PLUS,
            161 => Machine::EM_CYPRESS_M8C,
            162 => Machine::EM_R32C,
            163 => Machine::EM_TRIMEDIA,
            164 => Machine::EM_QDSP6,
            165 => Machine::EM_8051,
            166 => Machine::EM_STXP7X,
            167 => Machine::EM_NDS32,
            168 => Machine::EM_ECOG1X,
            169 => Machine::EM_MAXQ30,
            170 => Machine::EM_XIMO16,
            171 => Machine::EM_MANIK,
            172 => Machine::EM_CRAYNV2,
            173 => Machine::EM_RX,
            174 => Machine::EM_METAG,
            175 => Machine::EM_MCST_ELBRUS,
            176 => Machine::EM_ECOG16,
            177 => Machine::EM_CR16,
            178 => Machine::EM_ETPU,
            179 => Machine::EM_SLE9X,
            180 => Machine::EM_L10M,
            181 => Machine::EM_K10M,
            183 => Machine::EM_AARCH64,
            185 => Machine::EM_AVR32,
            186 => Machine::EM_STM8,
            187 => Machine::EM_TILE64,
            188 => Machine::EM_TILEPRO,
            189 => Machine::EM_MICROBLAZE,
            190 => Machine::EM_CUDA,
            191 => Machine::EM_TILEGX,
            192 => Machine::EM_CLOUDSHIELD,
            193 => Machine::EM_COREA_1ST,
            194 => Machine::EM_COREA_2ND,
            195 => Machine::EM_ARCV2,
            196 => Machine::EM_OPEN8,
            197 => Machine::EM_RL78,
            198 => Machine::EM_VIDEOCORE5,
            199 => Machine::EM_78KOR,
            200 => Machine::EM_56800EX,
            201 => Machine::EM_BA1,
            202 => Machine::EM_BA2,
            203 => Machine::EM_XCORE,
            204 => Machine::EM_MCHP_PIC,
            205 => Machine::EM_INTELGT,
            210 => Machine::EM_KM32,
            211 => Machine::EM_KMX32,
            212 => Machine::EM_EMX16,
            213 => Machine::EM_EMX8,
            214 => Machine::EM_KVARC,
            215 => Machine::EM_CDP,
            216 => Machine::EM_COGE,
            217 => Machine::EM_COOL,
            218 => Machine::EM_NORC,
            219 => Machine::EM_CSR_KALIMBA,
            220 => Machine::EM_Z80,
            221 => Machine::EM_VISIUM,
            222 => Machine::EM_FT32,
            223 => Machine::EM_MOXIE,
            224 => Machine::EM_AMDGPU,
            243 => Machine::EM_RISCV,
            247 => Machine::EM_BPF,
            252 => Machine::EM_CSKY,
            258 => Machine::EM_LOONGARCH,
            _ => Machine::Unknown(v),
        }
    }
}

impl std::fmt::Display for Type {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ET_NONE    => write!(f, "ET_NONE"),
            Self::ET_REL     => write!(f, "ET_REL"),
            Self::ET_EXEC    => write!(f, "ET_EXEC"),
            Self::ET_DYN     => write!(f, "ET_DYN"),
            Self::ET_CORE    => write!(f, "ET_CORE"),
            Self::ET_OS(v)   => write!(f, "ET_OS({:#06x})", v),
            Self::ET_PROC(v) => write!(f, "ET_PROC({:#06x})", v),
            Self::Unknown(v) => write!(f, "unknown({:#06x})", v),
        }
    }
}

impl std::fmt::Display for Machine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unknown(v) => write!(f, "unknown({:#06x})", v),
            other => write!(f, "{:?}", other),
        }
    }
}
